name: RELEASE

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Set up linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Lint
        run: make lint

      - name: Test
        run: make test
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Benchmark
        run: make benchmark

      - name: Build
        run: make build

  release:  
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Release
        uses: CupOfTea696/gh-action-auto-release@v1.0.0
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
          regex: "/^Release: #{semver}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

